config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end
  
  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end
  
  def create
    @location = Location.new(
      country: params["location"][:country],
      capital: params["location"][:capital],
      fun_fact: params["location"][:fun_fact]
    )

    if @location.save
      redirect_to @location, notice: 'Location has been created successfully.'
      flash[:notice] = 'Location has been created successfully.'
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])

    if @location.update(
      country: params["location"][:country] || location.country,
      capital: params["location"][:capital] || location.capital,
      fun_fact: params["location"][:fun_fact] || location.fun_fact
    )
    redirect_to @location, notice: 'Location was successfully updated.'
    flash[:notice] = 'Location was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_path, notice: 'Location was successfully deleted.'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(
      title: params["post"]["title"],
      content: params["post"]["content"],
      author: params["post"]["author"]
    )

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
      flash[:notice] = 'Post was successfully created'
    else
      render :new
    end
  end

  def  edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(
      title: params["post"]["title"] || post.title,
      content: params["post"]["content"] || post.content,
      author: params["post"]["author"] || post.author,
    )
    redirect_to @post, notice: 'Post was successfully updated.'
    flash[:notice] = 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully deleted.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog Api" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>
    
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, message| %>
      <div class="flash <%= key %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with model: @location do |form| %>
  <p>
    <%= form.label :country %><br>
    <%= form.text_field :country %>
  </p>

  <p>
  <%= form.label :capital %><br>
  <%= form.text_field :capital %>
  </p>

  <p>
  <%= form.label :fun_fact %><br>
  <%= form.text_area :fun_fact %>
  </p>

  <%= form.submit 'Add Country' %>

<% end %>

app/views/locations/edit.html.erb
<h1>Edit Country<h1>
<%= render 'form' %>
<%= link_to 'Back to Countries', locations_path %>

app/views/locations/index.html.erb
<h1>Countries</h1>

<% if @locations.any? %>
  <% @locations.each do |location| %>
    <div class="location">
    <h2><%= link_to location[:country], location_path(location[:id]) %></h2>
    </div>
  <% end %>
<% else %>
  <p>No locations available.</p>
<% end %>

<%= link_to 'Create Country', new_location_path %>

app/views/locations/new.html.erb
<h1>Add a New Country</h1>

<%= render 'form' %>

<% link_to 'Back to Countries', locations_path %>

app/views/locations/show.html.erb
<h1>Information</h1>

<h1><%= @location[:country] %></h1>

<p>Capital: <%= @location[:capital] %></p>
<p>Fun Fact: <%= @location[:fun_fact] %></p>

<%= link_to 'Back to Countries Index', locations_path %>
<br>
<br>
<%= link_to 'Edit Country Information', edit_location_path %>
<br>
<br>
<%= button_to 'Delete Country', @location, method: :delete, data: { turbo_confirm: 'Are you sure you want to delete this location?' } %>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>

  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>

  <%= form.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post<h1>
<%= render 'form' %>
<%= link_to 'Back to Posts', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% if @posts.any? %>
  <% @posts.each do |post| %>
    <div class="post">
      <h2><%= link_to post[:title], post_path(post[:id]) %></h2>
      <p>By: <%= post[:author] %></p>
      <p><%= post[:content] %></p>
    </div>
  <% end %>
<% else %>
  <p>No posts available.</p>
<% end %>

<%= link_to 'Create Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>

  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>

  <%= form.submit 'Create Post' %>

<% end %>

<%= link_to 'Back to Posts', posts_path %>

app/views/posts/show.html.erb
<h1>In the Posts Show View</h1>

<h1><%= @post[:title] %></h1>

<p>By: <%= @post[:author] %></p>
<p><%= @post[:content] %></p>

<%= link_to 'Back to Posts Index', posts_path %>
<br>
<br>
<%= link_to 'Edit Post', edit_post_path %>
<br>
<br>
<%= button_to 'Delete Post', @post, method: :delete, data: { turbo_confirm: 'Are you sure?' } %>